# Generated by Django 3.2.7 on 2021-09-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatami', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='featureList',
        ),
        migrations.DeleteModel(
            name='FeaturesList',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
